apiVersion: v1 
kind: Pod
metadata:
  name: product-service
spec:
  hostNetwork: true
  containers:
  - name: product-service
    image: product-service
    ports:
    - containerPort: 65130
      hostPort: 65130
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 65130

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
    - port: 65130
      protocol: TCP
  selector:
    app: product-service
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
