apiVersion: v1
kind: Secret
metadata:
  name: oauth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-service
  labels:
    app: oauth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-service
  template:
    metadata:
      labels:
        app: oauth-service
    spec:
      containers:
        - name: oauth-service
          image: oauth-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: oauth-service
  labels:
    app: oauth-service
spec:
  ports:
    - port: 9100
      protocol: TCP
  selector:
    app: oauth-service