apiVersion: v1
kind: Secret
metadata:
  name: zuul-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-server
  template:
    metadata:
      labels:
        app: zuul-server
    spec:
      containers:
        - name: zuul-server
          image: zuul-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  ports:
    - port: 8090
      protocol: TCP
  selector:
    app: zuul-server